#! /bin/bash

BASE="$HOME/.config/bootstrap"
YADM_CLASSES="$BASE/yadm-classes"
MANAGERS="$BASE/package-manager.json"
MAC_COREUTILS="$BASE/macos-gnu-coreutils"
source "$HOME/.config/yadm/bootstrap-helpers/helpers.sh"

# -- jq check --
if ! cmd_exists jq; then
	echo "Please install jq (https://stedolan.github.io/jq/download/) and try again"
	exit 1
fi


# -- Detect package manager --
MANAGER=""
if [[ $OSTYPE == "linux-gnu" ]]; then
	for key in $(jq 'keys[]' "$MANAGERS"); do
		key=${key//\"/}
		if cmd_exists "$key"; then
			MANAGER=$key
			break
		fi
	done
elif [[ $OSTYPE == "darwin"* ]]; then
	if ! cmd_exists "brew"; then
		echo "Intalling homebrew"
		eval "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	fi
	MANAGER="brew"
fi

if [[ $MANAGER == "" ]]; then
	echo "Couldn't find the pacakage manager for this system. Please add it to $MANAGERS"
	exit 1
fi

echo "Detected package manager as $MANAGER"

INSTALL_CMD="sudo $MANAGER $(jq .$MANAGER.install "$MANAGERS" | sed s/\"//g)"
UPDATE_CMD="sudo $MANAGER $(jq .$MANAGER.update "$MANAGERS" | sed s/\"//g)"

# -- Update --
# echo "Performing system update"
# $UPDATE_CMD

#### CLI Setup #### 

# -- Bash --
if ! echo "$SHELL" | grep "bash" > /dev/null 2>&1; then
	echo "Chaging shell to bash"
	chsh -s /bin/bash
fi

# -- Gnu Utils for Mac --
if [[ $OSTYPE == "darwin"* ]]; then
	for pkg in $MAC_COREUTILS; do
		install_if_missing "$pkg"
	done
fi

# -- Fzf --
if ! install_if_missing fzf; then
	echo "Please install fzf then try again. See https://github.com/junegunn/fzf#installation"
	exit 1
fi

# -- Yadm setup --
if [[ $(yadm config local.class) == "" ]]; then
	echo "Please choose a system type (yadm local.class)"
	sleep 2
	YADM_CLASS=$(fzf < "$YADM_CLASSES")
	yadm config local.class "$YADM_CLASS"
	yadm alt
	yadm checkout "$HOME" > /dev/null 2>&1
fi

# -- Tmux --
install_if_missing tmux

# -- vim-plug -- 
if [ ! -f ~/.vim/autoload/plug.vim ]; then
	printf "\nInstalling vim-plug"
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	vim '+PlugInstall' '+UpdateRemotePlugins' 
fi

# -- Neovim --
install_if_missing nvim --pkg-name neovim

# -- wget --
install_if_missing wget

#### GUI Setup ####
[[ $(yadm config local.class) == "linux-server" ]] && exit 0

# -- Alacritty --
install_if_missing alacritty --brew_opts --cask 

if [[ $(yadm config local.class) == "linux-gui" ]]; then
	if [[ ! $XDG_CURRENT_DESKTOP =~ "GNOME" ]]; then
		echo "Please install GNOME and try again"
		exit 1
	fi

	[[ -f "$HOME/.dconf-settings.ini" ]] && dconf load / < "$HOME/.dconf-settings.ini"

	install_if_missing rofi

	! (gnome-extensions list | grep pop-shell > /dev/null 2>&1) && install_if_missing gnome-shell-extension-pop-shell --pacman_alt yay
fi

if [[ $OSTYPE == "Darwin*" ]]; then
	install_if_missing karabiner-elements --brew_opts --cask 
fi


printf "Complete! Please log out and log back in.\n"
