#! /bin/sh

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config window_gap 6
bspc config border_width 1 

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Per-application preferences
bspc rule -a "firefox" desktop=^2
bspc rule -a "vs code @ fb" desktop=^3
bspc rule -a "Vs code @ fb" desktop=^3
bspc rule -a "qemu" desktop=^3
bspc rule -a "Files" state=floating rectangle="900x500"
bspc rule -a "nemo" state=floating rectangle="900x500"
bspc rule -a "Wpg" state=floating
bspc rule -a "Zathura" state=tiled
bspc rule -a "gnome-control-center" state=floating
bspc rule -a "Gnome-control-center" state=floating
bspc rule -a "gnome-calculator" state=floating
bspc rule -a "Gnome-calculator" state=floating
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/spotify-rules";

# Colors
[[ -f "$HOME/.cache/wal/colors.sh" ]] && source $HOME/.cache/wal/colors.sh

bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color1"

# A bit hacky
pgrep -x picom > /dev/null 2>&1 || $HOME/.xinitrc

[[ -f "$HOME/bin/update-monitors" ]] && $HOME/bin/update-monitors
