#! /bin/sh

# sxhkd started in .xprofile
# pgrep -x sxhkd > /dev/null || sxhkd & 

bspc monitor HDMI-2 -d 1 2 3 4 5 6 7 8 9 0
# bspc monitor eDP-1 -n 1 -d 7 8 9 0

bspc config border_width 0
bspc config window_gap 8

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config borderless_monocle true

# Per-application preferences
bspc rule -a "firefox" desktop=^2
bspc rule -a "Google-chrome" desktop=^2
bspc rule -a "vs code @ fb" desktop=^3
bspc rule -a "Vs code @ fb" desktop=^3
bspc rule -a "qemu" desktop=^3
bspc rule -a "Files" state=floating rectangle="900x500"
bspc rule -a "nemo" state=floating rectangle="900x500"
bspc rule -a "Wpg" state=floating
bspc rule -a "Zathura" state=tiled
bspc rule -a "gnome-control-center" state=floating
bspc rule -a "Gnome-control-center" state=floating
bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/spotify-rules";

# Colors
[[ -f "$HOME/.cache/wal/colors.sh" ]] && source $HOME/.cache/wal/colors.sh

bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color0"

# Polybar
[[ -f "$HOME/.config/polybar/launch.sh" ]] && source $HOME/.config/polybar/launch.sh

# A bit hacky
pgrep -x picom > /dev/null || $HOME/.xinitrc
